### ISSUE TITLE
[Win] VM can not start if gateway interface is ppp miniport

### ISSUE THREAD

**Issue by btemir** [subutai-io/installers#117]
Could not install on machine having pppoe (or any non-physical) gateway interface. Actually in thins case we have network with one machine without dhcp. But need to check possibility to install VM in that situation.

> 2016-12-01 17:16:33.5695|INFO|Deployment.VMs|vm 1: subutai-201612010455 starting: executing: "vboxmanage startvm --type headless subutai-201612010455 "
> 2016-12-01 17:16:33.5695|INFO|Deployment.VMs|vm 1: subutai-201612010455 stdout: Waiting for VM "subutai-201612010455" to power on...
> 
> 2016-12-01 17:16:33.5695|INFO|Deployment.VMs|vm 1: subutai-201612010455 stdout: vboxmanage.exe: error: Nonexistent host networking interface, name 'ÌåãàËàéí' (VERR_INTERNAL_ERROR)
> vboxmanage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole
> 

from log:
[2016-12-01_Subutai_install_log.txt](https://github.com/subutai-io/installers/files/626318/2016-12-01_Subutai_install_log.txt)

![pasted image at 2016_12_01 17_43](https://cloud.githubusercontent.com/assets/16958983/20822017/63779e88-b871-11e6-90ab-f7ba94211ab0.png)

![pasted image at 2016_12_01 17_51](https://cloud.githubusercontent.com/assets/16958983/20822022/714ab734-b871-11e6-9861-6651c944a356.png)

![pasted image at 2016_12_01 17_54](https://cloud.githubusercontent.com/assets/16958983/20822024/784256e6-b871-11e6-80e5-9b449266950d.png)

**Comment by btemir** [comment]
on other machine 
[tt_2016-12-07_Subutai_install_log.txt](https://github.com/subutai-io/installers/files/635311/tt_2016-12-07_Subutai_install_log.txt)

[adapter_2016-12-09_Subutai_install_log.txt](https://github.com/subutai-io/installers/files/641377/adapter_2016-12-09_Subutai_install_log.txt)

> subutai-201612090150 starting: executing: "vboxmanage startvm --type headless subutai-201612090150 "
> 2016-12-09 01:55:51.1889|INFO|Deployment.VMs|vm 1: subutai-201612090150 stdout: Waiting for VM "subutai-201612090150" to power on...
> 
> 2016-12-09 01:55:51.1889|INFO|Deployment.VMs|vm 1: subutai-201612090150 stdout: vboxmanage.exe: error: Nonexistent host networking interface, name 'Intel(R) Centrino(R) Wireless-N 2230' (VERR_INTERNAL_ERROR)
> vboxmanage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole
>

**Comment by btemir** [comment]
if bridged interface disabled, VM can start and installation finished successfully. But we can not Launch Subutai Social Console in this case. `sudo subutai info ipaddr` gives address 10.0.3.15, management console is not reachable by this address, but it's reachable via host-only interface.
[2016-12-12_Subutai_install_log (1).txt](https://github.com/subutai-io/installers/files/646827/2016-12-12_Subutai_install_log.1.txt)

**Comment by btemir** [comment]
pppoe on virtualbox:
https://forums.virtualbox.org/viewtopic.php?f=9&t=18587
http://chamilad.github.io/blog/2014/08/05/pppoe-on-virtualbox/

**Comment by akylbekesenaliev** [comment]
Tested this issue on my friend's machine: 
1. Started VM and Tray 
2. from RH got ouput of `ifconfig eth1` command :  https://192.168.56.100:8443/
3. Pasted the address into Chrome Browser and opened Subutai Management
![image](https://cloud.githubusercontent.com/assets/17665678/21311911/d1c1297c-c613-11e6-869f-22e41acb8126.png)
![image](https://cloud.githubusercontent.com/assets/17665678/21311912/d57b7504-c613-11e6-888a-739e52827324.png)
I was able to create environments from SS and Hub: 
![image](https://cloud.githubusercontent.com/assets/17665678/21311914/da7bea16-c613-11e6-8392-f7b403875c20.png)
![image](https://cloud.githubusercontent.com/assets/17665678/21311944/fa901958-c613-11e6-9bfc-2062d3d9e5cb.png)

I was able to SSH from Tray : 
![image](https://cloud.githubusercontent.com/assets/17665678/21311926/e885a412-c613-11e6-8487-d5ea750ee9c1.png)
but failed to SSH from HUB because I had error while trying to install E2E plugin on my friend's computer : 
![image](https://cloud.githubusercontent.com/assets/17665678/21311981/24170b88-c614-11e6-9f6f-57db4de56fb5.png)
But looks like this issue ^ is very solvable .. - > 
![image](https://cloud.githubusercontent.com/assets/17665678/21312000/3ae51ad0-c614-11e6-937f-0e60ffc4fe12.png)
Need to delete : `127.0.0.1       activate-sea.adobe.com127.0.0.1 clients2.google.com` from Hosts fie. 
so overall, testing went well, only one issue was encountered, the main parts are working as champ.
